### ISSUE TITLE
No android's framework ?

### ISSUE THREAD

**Issue by CaichaoGitHub** [facemoji/mocap4face#1]
thanks for your great work 
i only found ios framework , no android ?

**Comment by karelp** [comment]
Hi, we host our Android frameworks in our Artifactory for your convenient use as a Gradle dependency, see https://github.com/facemoji/mocap4face#-installation. You can also download the aar package from the [releases page of this repository](https://github.com/facemoji/mocap4face/releases/tag/0.1.0) but then you will need to add transitive dependencies yourself.

Look at the [android-example](https://github.com/facemoji/mocap4face/tree/main/android-example) project (just open it in Android Studio) to see how to use the Android framework in action.

**Comment by CaichaoGitHub** [comment]
> Hi, we host our Android frameworks in our Artifactory for your convenient use as a Gradle dependency, see https://github.com/facemoji/mocap4face#-installation. You can also download the aar package from the [releases page of this repository](https://github.com/facemoji/mocap4face/releases/tag/0.1.0) but then you will need to add transitive dependencies yourself.
> 
> Look at the [android-example](https://github.com/facemoji/mocap4face/tree/main/android-example) project (just open it in Android Studio) to see how to use the Android framework in action.

thanks for replay , i had an another question : i saw your website says you framework could fit face in 50000 vertices ,  could you framework output the face for developer ?

**Comment by karelp** [comment]
We currently removed this feature for our mobile models as it was computationally more costly. When we release desktop versions we will consider adding this feature to mocap4face.
