### ISSUE TITLE
Any plans for Windows & MacOS Support?

### ISSUE THREAD

**Issue by aaronn** [facemoji/mocap4face#11]
I'm guessing if this is already cross-platform on Android, Web, and iOS that this an upcoming features. Just curious since we'd love to use this everywhere if possible

**Comment by karelp** [comment]
Hey, yes, we do plan to add support for desktop platforms, currently we focus on improving the SDK first and fixing existing platforms. Mac will arrive much sooner than Windows as the APIs are mostly identical to iOS. I expect Mac to happen within the next 2-3 months.

**Comment by aaronn** [comment]
@karelp Anything new on the Mac? We primarily just want to be able to use the full camera width when running under M1 catalyst. We don't need the full feature-set, but macOS forces "non-mac" frameworks to use a cropped iPhone-like camera view even on the Mac which has a much wider view.
