### ISSUE TITLE
Activate webcam in javascript

### ISSUE THREAD

**Issue by nicoprofe** [facemoji/mocap4face#14]
Hey! How can I activate my webcam by code instead of the .MP4 by default? Talking about Mocap4face for web javascript. Thanks

**Comment by karelp** [comment]
Hey, the webcam button gets activated when your device supports a webcam. Note that you need a HTTPs connection in all modern browsers for your webcam to work so the browser usually reports "no webcam" on plain http localhost. We have a [special script to start HTTPs on localhost](https://github.com/facemoji/mocap4face/blob/b67dc8e7e29e170cc83d1a8908ee48b6a092ea63/js-example/package.json#L8) (with a self-signed certificate), you can run it by calling `npm run dev_https`.
