### ISSUE TITLE
Get Blendshapes values

### ISSUE THREAD

**Issue by nicoprofe** [facemoji/mocap4face#15]
How to get the Slider/Blendshapes values in javascript and convert it to json?

**Comment by karelp** [comment]
Hey, check out the code in our examples that extracts the blendshapes for the UI: https://github.com/facemoji/mocap4face/blob/b67dc8e7e29e170cc83d1a8908ee48b6a092ea63/js-example/src/index.ts#L47

You can of course save them to JSON or do whatever else you like at that point.
