### ISSUE TITLE
Stop face tracking

### ISSUE THREAD

**Issue by Nawarius** [facemoji/mocap4face#17]
Hello. Thanks for the great face tracking library!

How can I stop tracking? Something like a dispose/destroy function?

I am using this library in web (js)

**Comment by karelp** [comment]
Hi, it’s sufficient to just stop playback on the video element you pass in. Either by setting `videoElement.srcUrl = null` or by calling `videoElement.pause()`. You can also stop the tracker loop by simply not passing the webcam data to the tracker instance.
