### ISSUE TITLE
[Question]: Is this Lib compatible with react-native?

### ISSUE THREAD

**Issue by shamxeed** [facemoji/mocap4face#2]
It would be incredibly awesome to include this library in my React-Native start-up App but I wonder whether there's React-Native compatible SDK?

Thanks!!!

**Comment by karelp** [comment]
We currently only support native libraries, should be easy to wrap them to React Native bindings. I’m keeping this issue open as we might add an official RN wrapper in the future.

**Comment by shamxeed** [comment]
Thank you for your response @karelp! And I’m looking forward to that!🤩
