### ISSUE TITLE
OpenGLResizer20: setup OES texture: glError 1282: invalid operation

### ISSUE THREAD

**Issue by pengzhenkun** [facemoji/mocap4face#21]
使用 Android 版本打开 Activity 正常，关闭页面再次启用的时候出现 
OpenGLResizer20: setup OES texture: glError 1282: invalid operation

onCameraImageArkitLink(cameraTexture: OpenGLTexture)

cameraTexture = null

**Comment by karelp** [comment]
Fixed in 0.4.0
