### ISSUE TITLE
Consider Releasing ML models

### ISSUE THREAD

**Issue by no-1ne** [facemoji/mocap4face#24]
Sorry to see alter being discontinued, like the stable  diffusion guy would you be considerate to consider releasing alter's tfjs models. 
TIA

**Comment by no-1ne** [comment]
my bad you already did. you are awesome

**Comment by MarcoG5** [comment]
> 

@no-1ne where can I find this tfjs model ?

**Comment by no-1ne** [comment]
https://github.com/facemoji/mocap4face/releases
