### ISSUE TITLE
can not find any documents about how to build a app using facemoji SDK

### ISSUE THREAD

**Issue by danlanxiaohei** [facemoji/mocap4face#3]
i want to build a app like the offical facemoji app, but the demo code is so simple, the SDK even has no document.

can anyone tell me how to use the SDK to build a facemoji app ?

**Comment by danlanxiaohei** [comment]
@robinraszka

**Comment by karelp** [comment]
Hi, the demo code shows 99 % of the mocap4face capabilities. Note that this is only the face tracking technology we have, not the full avatar SDK which is coming later this year/early 2022.

You can of course build a facemoji-like app with mocap4face but you will have to create all the avatars yourself.

**Comment by danlanxiaohei** [comment]
got it, thank!
