### ISSUE TITLE
Mainactivity  re-opened cannot be traced

### ISSUE THREAD

**Issue by cike978** [facemoji/mocap4face#5]
Only the first open MainActivity can be tracked.  when back to SplashActivity and reopen Mainactivity the track result is null. 

The test code is as follows（modify SplashAtivity）：

    override fun onResume() {
        super.onResume()
        Timer("Splash", false).schedule(5000) {
            startMainActivity()
        }
    }

**Comment by cike978** [comment]
The Repetition steps is when the app is not killed, go back to the SplashActivity and enter MainActicity again

**Comment by will4621d** [comment]
Same problem, the error is "OpenGLResizer20: setup OES texture: glError 1282: invalid operation"

**Comment by will4621d** [comment]
@karelp Hi, is there any update about this issue?

**Comment by karelp** [comment]
Hi, I’m able to reproduce it but it takes quite a bit of internal refactor to get fixed, the problem is that sometimes when closing/reopening activities the OpenGL context gets lost without the camera tracker getting information about it. Will probably need to rethink the way we handle OpenGL to work around this problem.

**Comment by lonelyssl** [comment]
I also encountered this mistake and urgently need to solve it. Is there any way to solve this problem now?  thank you

**Comment by karelp** [comment]
Hey, yes, the workaround for now is to create new CameraWrapper when the activity gets restarted.

**Comment by pengzhenkun** [comment]
Is there any solution to this problem? It is in urgent need of repair. Thank you

**Comment by pengzhenkun** [comment]
> 我也遇到了这个错误，迫切需要解决它。现在有办法解决这个问题吗？谢谢您



> I also encountered this mistake and urgently need to solve it. Is there any way to solve this problem now? thank you

Is there a solution?

**Comment by pengzhenkun** [comment]
> I also encountered this mistake and urgently need to solve it. Is there any way to solve this problem now? thank you

Is there a solution?

**Comment by karelp** [comment]
Fixed in 0.4.0.
